Demo in master
TheSecondThread/FivaproljoTasks pull request #17
Opened 2020-03-17 19:26 UTC by DanielGabitov

2020-03-17 21:36 UTC, LebedevEA commented
кажется, если это сейчас мерижить то две папочки потеряются

2020-04-01 09:08 UTC, alexander-bzikadze requested changes
Оставил свои комментарии, по возможности улучшите код

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Background.h
> +#define DEMO_BACKGROUND_H
#pragma once намного легче менеджить, и это читаемее
Следует понимать, что #indef ... way ранее был единственным, но сейчас он безнадежно устарел

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Background.h
> +    virtual QPainterPath shape() const;
А с какой целью данный метод является virtual?
В силу специфики C++, вы должны четко понимать, что стоит за каждым вашим шагом -- что именно вы делаете и почему

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Block.h
> +    enum { Type = UserType + 1 };
Ват? 🤔

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Block.h
> +    size_t block_height = 50;
Следует избегать паблик полей, они противоречат OOP. Более конкретно, таким образом вы не можете поддерживать инкапсуляцию, то есть ваш объект не будет гарантировано переходить из корректного состояния в корректное. Например, что если кто-либо присвоит block_width невероятно большое значение? Больше чем размер модели? Будет ли это корректное состояния.
Так как это учебных проект, предлагаю полностью запретить паблик поля. Да, C++ это староватый язык, он не умеет в проперти, но тем не менее.

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Block.h
> +    std::queue<std::string> next_texture_;
Лучше явно проинициализировать и не полагаться на компилятор, что тот вызовет дефолтный конструктор

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Controller.h
> +    void keyReleaseEvent(QKeyEvent *event) override;
А какой наследний будет пользоваться этими полями? Почему они протектид?

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Controller.h
> +    class PlayerManipulator_ {
Не вижу использования класса в хедере. Может его проще полностью сдвинуть в cpp?

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Controller.h
> +    class PlayerManipulator_ {
А для чего ему underscore в названии? :D

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Controller.h
> +	PlayerManipulator_(Player* player);
Хммм, казалось бы, есть умные указатели 🤔

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Controller.h
> +};
Легче держать разные классы в разных файлах. Их так легче искать, и логику проще разделять.
Так как проект учебный, предлагаю этому следовать

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Object.h
> +class Object : public QGraphicsPixmapItem {
Модель и View смешаны. В Object лучше сосредоточиться на необходимом в модели, а не в том, Как его следует отображать

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Scene.h
> +    void add_background(QString image);
`QString image`
День когда земля остановилась
Выглядит будто кто-то передает изображение как байты в строке)
Надеюсь, что нет
* **image** в данном случае не дескриптив
* QString следует генерировать внутри как внутреннюю логику, кажется достаточно стандартной строки

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/include/Utilities.h
> +};
Утилс в принципе не дескриптив
Я бы точно не догадался что внутри енамы)) А они много где используются, так что я бы их искал
Не стесняйтесь пользоваться файловой системой и namespace-ами для структурирования своего кода

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Background.cpp
> +    return QPainterPath();
Хм, что это?
Кто-то будет это менять? Если нет, то можно
* возвращать один и тот же статический объект, объявленный в этом файле
* можно возвращать const объект

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Block.cpp
> +void Block::add_color(int color) {
`int color`
Хм 🤔 
Что бы это ни значило

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Block.cpp
> +    recolor_timer_ = new QTimer(this);
`new` 😨 😨 😨 
Зачем?)

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Block.cpp
> +    next_texture_ = std::queue<std::string>(); // clear queue, mb race
https://stackoverflow.com/a/709161

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Block.cpp
> +    recolor_timer_->setInterval(50);
50 лучше вынести в какую-то конфигурацию, вряд ли это удобно настраивать отсюда
Либо это должна быть константа
Сейчас это совсем не дескриптив и сложно менеджить

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Controller.cpp
> +void Controller::runGame() { // later - add loop
"// later -" -> "// TODO: "

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Controller.cpp
> +void Controller::runGame() { // later - add loop
Контроллер запускает игру?
А как будете потом расширять когда несколько режимов будет? :)

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Controller.cpp
> +        player_manipulator_.press((Qt::Key) event->key()); //TODO cast
TODO следует выделять на отдельную строку, в конце его никто никогда не увидит

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Controller.cpp
> +        player_->change_direction();
Много общего кода, я думаю можно было лучше организовать

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Model.cpp
> +void Model::make_new_level(Scene *gs) {
Как-то так себе метод в плане расширения :)
Как планируете создавать другие уровни?)

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Player.cpp
> +        : color(BlockColor::GREEN), image("images/demo_player.png") {
Опять же, то о чем говорю
Игрок является объектом модели. Почему он еще и свой цвет настраивает?

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Scene.cpp
> +
Следует понимать, что это потом следует вынести во внешнюю конфигурацию

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/main.cpp
> +    return a.exec();
Вот как раз runGame можно было в мейне расписать :)

2020-04-01 09:08 UTC, alexander-bzikadze commented on demo/src/Scene.cpp
> +}
Очень много магических констант, слабо поддающихся объяснению

2020-05-03 10:48 UTC, merged